# Generated by Django 5.1.5 on 2025-02-15 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0006_payment_created_payment_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='tran_id',
            field=models.CharField(max_length=100),
        ),
    ]
